<div class="content-header">
  <h2 data-i18n="navigationBlacklist"></h2>
</div>
<p class="justify-text">
  <em data-i18n="blacklistLabelInformation"></em>
  <span class="small-text" data-i18n="blacklistTextInformation"></span>
  <a class="small-text" target="_blank" href="https://github.com/Robbendebiene/Gesturefy/wiki/Blacklist" data-i18n="linkAdditionalInformation"></a>
</p>
<hr>
<form id="blacklistForm" class="bl-form">
  <input name="urlPattern" autofocus class="bl-url-pattern-input">
  <button class="bl-add-button" type="submit" data-i18n="blacklistAddButton"></button>
</form>
<ul class="blacklist" id="blacklistContainer"></ul>
