<div class="content-header">
  <h2 data-i18n="navigationBlocklist"></h2>
</div>
<p class="justify-text">
  <em data-i18n="blocklistLabelInformation"></em>
  <span class="small-text" data-i18n="blocklistTextInformation"></span>
  <a class="small-text" target="_blank" href="https://github.com/Robbendebiene/Gesturefy/wiki/Blocklist" data-i18n="linkAdditionalInformation"></a>
</p>
<hr>
<form id="blocklistForm" class="bl-form">
  <input name="urlPattern" autofocus class="bl-url-pattern-input">
  <button class="bl-add-button" type="submit" data-i18n="blocklistAddButton"></button>
</form>
<ul class="blocklist" id="blocklistContainer"></ul>
