<div class="content-header">
  <h2 data-i18n="navigationExclusions"></h2>
</div>
<p class="justify-text">
  <em data-i18n="exclusionsLabelInformation"></em>
  <span class="small-text" data-i18n="exclusionsTextInformation"></span>
  <a class="small-text" target="_blank" href="https://github.com/Robbendebiene/Gesturefy/wiki/Exclusions" data-i18n="linkAdditionalInformation"></a>
</p>
<hr>
<form id="exclusionsForm" class="bl-form">
  <input name="urlPattern" autofocus class="bl-url-pattern-input">
  <button class="bl-add-button" type="submit" data-i18n="exclusionsAddButton"></button>
</form>
<ul class="exclusions" id="exclusionsContainer"></ul>
