<div class="content-header">
  <h2 data-i18n="navigationAbout"></h2>
</div>
<p class="small-spacing">
  <strong>
    <span data-manifest="name"></span>, Version: <span data-manifest="version"></span>
  </strong>
</p>
<p class="justify-text">
  <strong data-i18n="aboutLicense"></strong>
  GNU GPLv3
  Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
</p>
<hr>
<p>
  <strong data-i18n="aboutContributors"></strong>
  <a target="_blank" href="https://github.com/Robbendebiene/Gesturefy/graphs/contributors">Github</a>,
  <a target="_blank" href="https://crowdin.com/project/gesturefy">Crowdin</a>
</p>
<hr>
<ul class="horizontal-list">
  <li><a target="_blank" href="https://github.com/Robbendebiene/Gesturefy/issues" data-i18n="aboutLinkBug"></a></li>
  <li><a target="_blank" href="https://github.com/Robbendebiene/Gesturefy" data-i18n="aboutLinkCode"></a></li>
  <li><a target="_blank" href="https://addons.mozilla.org/firefox/addon/gesturefy/" data-i18n="aboutLinkAddon"></a></li>
</ul>

