<div class="content-header">
  <h2>
    <locale-text key="navigationAbout"></locale-text>
  </h2>
</div>
<p class="small-spacing">
  <strong>
    <span data-manifest="name"></span>, Version: <span data-manifest="version"></span>
  </strong>
</p>
<p class="justify-text">
  <strong>
    <locale-text key="aboutLicense"></locale-text>
  </strong>
  GNU GPLv3
  Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
</p>
<hr>
<p>
  <strong>
    <locale-text key="aboutContributors"></locale-text>
  </strong>
  <a target="_blank" href="https://github.com/Robbendebiene/Gesturefy/graphs/contributors">Github</a>,
  <a target="_blank" href="https://crowdin.com/project/gesturefy">Crowdin</a>
</p>
<hr>
<ul class="horizontal-list">
  <li>
    <a target="_blank" href="https://github.com/Robbendebiene/Gesturefy/issues">
      <locale-text key="aboutLinkBug"></locale-text>
    </a>
  </li>
  <li>
    <a target="_blank" href="https://github.com/Robbendebiene/Gesturefy">
      <locale-text key="aboutLinkCode"></locale-text>
    </a>
  </li>
  <li>
    <a target="_blank" href="https://addons.mozilla.org/firefox/addon/gesturefy/">
      <locale-text key="aboutLinkAddon"></locale-text>
    </a>
  </li>
</ul>

